#!/bin/bash

module purge

# Main OmpSs-2 utilities used in Examples and Exercises:
module load intel/2017.1
module load impi/2017.1
module load mkl/2017.1
module load bsc
module load ompss-2/2019.06
module load tampi/git
module load gcc/6.2.0
module load extrae
module load paraver

# You should provide a job scheduler header for one node execution
cat > $OSS2EE_CONFIG_DIR/job-sched-1n << EOF
#BSUB -n 16
#BSUB -R "span[ptile=16]"
#BSUB -oo oss-2-ee_%J.out
#BSUB -eo oss-2-ee_%J.err
##BSUB -U prace
#BSUB -J oss-2-ee
#BSUB -W 00:15
#BSUB -x
EOF

# You should provide a job scheduler header for multi-node execution
cat > $OSS2EE_CONFIG_DIR/job-sched-mn << EOF
#BSUB -n 2
#BSUB -R "span[ptile=2]"
#BSUB -oo oss-2-ee_%J.out
#BSUB -eo oss-2-ee_%J.err
##BSUB -U prace
#BSUB -J oss-2-ee
#BSUB -W 00:15
#BSUB -x
EOF

# Extra package configuration (building purposes): MPI
export OSS2EE_MPI_LIB_DIR=/apps/INTEL/2016.3.067/impi/5.1.3.210/intel64/lib
export OSS2EE_MPI_INC_DIR=/apps/INTEL/2016.3.067/impi/5.1.3.210/intel64/include

# Extra package configuration (building purposes): MKL
export OSS2EE_MKL_LIB_DIR=/opt/intel/mkl/lib/intel64/
export OSS2EE_MKL_INC_DIR=/opt/intel/mkl/include/

# Extra package configuration (building purposes): ATLAS
export OSS2EE_ATL_LIB_DIR=/apps/ATLAS/3.10.2/lib
export OSS2EE_ATL_INC_DIR=/apps/ATLAS/3.10.2/include

# Extra package configuration (for building purposes): TAMPI
export OSS2EE_TAMPI_LIB_DIR=$TAMPI_HOME/lib
export OSS2EE_TAMPI_INC_DIR=$TAMPI_HOME/include

# Command for compiling and running hybrid MPI programs
export OSS2EE_MPICC_COMMAND="mpiicc"
export OSS2EE_MPICXX_COMMAND="mpiicpc"
export OSS2EE_MPIRUN_COMMAND="mpirun"

# Put all Nanos6 feature by default
unset NANOS6_CONFIG_OVERRIDE
